<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="K548LTRV" failures="1" tests="1" name="Default test" time="13.909" errors="0" timestamp="2024-04-18T12:12:13 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="13.604">
    <failure type="java.lang.AssertionError" message="expected [Deposit Successfull] but found [Deposit Successful]">
      <![CDATA[java.lang.AssertionError: expected [Deposit Successfull] but found [Deposit Successful]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at stepdefinitions.CustomerLogin_Test.check_whether_the_money_has_been_credited(CustomerLogin_Test.java:52)
at âœ½.Check whether the money has been credited(file:///C:/Users/268896/eclipse-workspace/XYZbank/src/test/resources/features/CustomerLogin.feature:29)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
