<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-04-18T12:11:59 IST" name="Default suite" finished-at="2024-04-18T12:12:13 IST" duration-ms="13909">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:runner.TestRunner@2aceadd4]" name="runScenario" class="io.cucumber.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test started-at="2024-04-18T12:11:59 IST" name="Default test" finished-at="2024-04-18T12:12:13 IST" duration-ms="13909">
      <class name="runner.TestRunner">
        <test-method is-config="true" signature="setUpClass(org.testng.ITestContext)[pri:0, instance:runner.TestRunner@2aceadd4]" started-at="2024-04-18T12:11:59 IST" name="setUpClass" finished-at="2024-04-18T12:12:00 IST" duration-ms="242" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@54e02f6a]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:runner.TestRunner@2aceadd4]" started-at="2024-04-18T12:12:00 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-04-18T12:12:13 IST" duration-ms="13604" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Login with manager created account"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Login"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Deposit Successfull] but found [Deposit Successful]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Deposit Successfull] but found [Deposit Successful]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at stepdefinitions.CustomerLogin_Test.check_whether_the_money_has_been_credited(CustomerLogin_Test.java:52)
at âœ½.Check whether the money has been credited(file:///C:/Users/268896/eclipse-workspace/XYZbank/src/test/resources/features/CustomerLogin.feature:29)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:runner.TestRunner@2aceadd4]" started-at="2024-04-18T12:12:13 IST" name="tearDownClass" finished-at="2024-04-18T12:12:13 IST" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- runner.TestRunner -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
